### ISSUE TITLE
Production Ready

### ISSUE THREAD

**Issue by FaisalAbid** [ThinkSimple/flutter_simple_shopify#1]
The ReadMe says its not production ready. What's missing from getting to production ready?

**Comment by ThinkSimple** [comment]
Hello Faisal, we developed this library to create our own Shopify App and within the creation of our app, we started seeing missing functionality and still too many errors.
We work day to day on our Shopify app and just fix upcoming errors.
Feel free to use the library and tell us where you find errors/mistakes.

**Comment by FaisalAbid** [comment]
Thanks!

**Comment by matte5031** [comment]
Very nice job! Would be very nice to use when ready! In the meantime, do you guys know if we're allowed to redirect to the shopify homepage to checkout products or does it break the app stores guidelines?

**Comment by ThinkSimple** [comment]
Hello matte, that is actually the way to go as far as we know.
Every checkout contains a webUrl which you can simply open up in a webview.
There are actually graphql mutations that suggest that a in-app checkout is possible, (eg. with stripe)
but after asking specifically in the forum we did not get a proper answer.
Shopify has a guide how to implement Stripe with the storefront API but we are not able to do it.

**Comment by FaisalAbid** [comment]
@matte5031 - Im rewriting an app thats already in production, it redirects to checkout on webview, and Apple does not seem to have a problem with that

**Comment by lndavis6** [comment]
Hey! Any updates on production?

**Comment by ThinkSimple** [comment]
Hey @lndavis6 We almost finished creating our own app, and we fixed many bugs along the way, there still are some TODO's left for me but these are minor ones.
Feel free to use the library, because every issue helps us.
Our app used most of the functionality from the library, but a small portion remains untested (mostly blog).
As mentioned every issue helps us get faster to the endgoal so I would advise trying the library out.

**Comment by lndavis6** [comment]
Thank you so much! Will do.
