### ISSUE TITLE
Not able to get products from collections

### ISSUE THREAD

**Issue by hetkpatel** [ThinkSimple/flutter_simple_shopify#30]
After getting the collections from my Shopify store, I try to get the products within each collection using `.products`. But every time I get an empty list.

Currently, as a work-around, I'm using `Store.getAllProductsFromCollectionById()` and passing the `collectionId` but its taking a really long time to process through all my collections and retrieve the product list and information from each collection.

I don't know if this is an issue with how I have my collection and products set up in my Shopify account or regarding this plugin.

**Comment by ThinkSimple** [comment]
Hello, sorry it took me so long to get back to you.
You are actually doing this the right way, when we were designing our app we came up with the problem that the getAllCollections query was extremely inefficient because we would fetch ALL PRODUCTS in ALL COLLECTIONS.
The query in getAllCollections is optimized for you to get the id's quickly and simply use getAllProductsFromCollectionById() for you to get products.
Hope I could help.

**Comment by hetkpatel** [comment]
Got it! Thank you for your reply.
