### ISSUE TITLE
Type mismatch error in getAllProductsFromCollectionById

### ISSUE THREAD

**Issue by nishiths23** [ThinkSimple/flutter_simple_shopify#4]
When i try to call `getAllProductsFromCollectionById` I get the following exception:

"Type mismatch on variable $sortKey and argument sortKey (ProductSortKeys / ProductCollectionSortKeys): Undefined location"

**Comment by ThinkSimple** [comment]
Which version are you using?

**Comment by nishiths23** [comment]
I am using 0.0.16-alpha version

**Comment by ThinkSimple** [comment]
Quite weird, sort key was not even a variable in this query in "getAllProductsFromCollectionById".
However i pushed a new update 0.0.17-alpha.
It comes with the actual optional parameters for reversing the fetched list and for giving a sort key.
I dont know why that wasn't in there before since i announced these changes in 0.0.15-alpha.
As the new parameters got in you should check if every functions works like before and if not, double check the parameters that are required by the function, because i kind of messed up at some functions.

**Comment by nishiths23** [comment]
The new version worked. Thank you.
